services:
  db:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017

  server:
    build:
      context: .
    ports:
      - 3000:3000

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - 80:80
